export const RETRIEVE_USER_INFO = "RETRIEVE_USER_INFO";
export const USER_INFO_RETRIEVED = "USER_INFO_RETRIEVED";
export const GET_SETTINGS = "GET_SETTINGS";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
